#!/bin/bash
cd $(dirname $0)
job="$1" ; if [ -z "$job" ] ; then job="test" ; fi
case $job in


	test)
		dart test/life.test.dart
		;;


	js-test)
		frogc test/life.test.dart
		;;


	run)
		dart lub/main.dart
		;;


	js)
		frogc lib/main.dart
		;;


esac
